# Generated by Django 4.2.9 on 2024-02-10 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WasteBin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.CharField(max_length=32)),
                ('latitude', models.CharField(max_length=32)),
                ('area', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='WasteBinData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('wet', models.FloatField()),
                ('metal', models.FloatField()),
                ('other_waste', models.FloatField()),
                ('recyclable', models.FloatField()),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classification_model.wastebin')),
            ],
        ),
        migrations.CreateModel(
            name='DailyBinSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('wet', models.FloatField()),
                ('metal', models.FloatField()),
                ('other_waste', models.FloatField()),
                ('recyclable', models.FloatField()),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classification_model.wastebin')),
            ],
        ),
    ]
