# Generated by Django 5.0.1 on 2024-01-24 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WasteBin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.CharField(max_length=32)),
                ('latitude', models.CharField(max_length=32)),
                ('area', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='WasteBinData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('wet_organic', models.FloatField()),
                ('dry_organic', models.FloatField()),
                ('non_recyclable', models.FloatField()),
                ('recyclable', models.FloatField()),
                ('last_sanitized', models.DateTimeField()),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classification_model.wastebin')),
            ],
        ),
    ]
