# Generated by Django 5.0.1 on 2024-01-24 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification_model', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyBinSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('wet_organic', models.FloatField()),
                ('dry_organic', models.FloatField()),
                ('non_recyclable', models.FloatField()),
                ('recyclable', models.FloatField()),
                ('last_sanitized', models.DateTimeField()),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classification_model.wastebin')),
            ],
        ),
    ]
